name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  check:
    uses: moyarich/reusable-workflows/.github/workflows/reusable_node-ci.yml@main
    with:
      node-version: "24"
      package-directory: "."
    secrets:
      package-token: ${{ secrets._GITHUB_TOKEN }}
