name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  check:
    uses: moyarich/actions/.github/workflows/reusable_node-ci.yml@d28dc4fae24cb84b5e9acea2ac1f8cde5f95297e
    with:
      node-version: "24"
    secrets:
      package-token: ${{ secrets._GITHUB_TOKEN }}
