name: Deploy playground to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  pages: write
  id-token: write

jobs:
  pages:
    uses: moyarich/reusable-workflows/.github/workflows/reusable_github-pages.yml@main
    with:
      node-version: "24"
      build-command: npm run build:playground -- --base=/css-color-parser/
      output-directory: apps/playground/dist
    secrets:
      package-token: ${{ secrets._GITHUB_TOKEN }}
