name: Publish package

on:
  workflow_dispatch:
    inputs:
      package-directory:
        description: Package location
        required: true
        default: packages/css-color-parser
        type: string
      version:
        description: Exact version to publish; empty uses package.json
        required: false
        default: ""
        type: string
      registry:
        description: Package registry
        required: true
        type: choice
        options:
          - github
          - npm
        default: github
      tag:
        description: Distribution tag
        required: true
        default: latest
        type: string

permissions:
  contents: write
  packages: write

jobs:
  publish:
    uses: moyarich/actions/.github/workflows/reusable_npm-publish.yml@c37643656679bec74b2702fc61bf043fe23c0aa7
    with:
      dry-run: false
      package-directory: ${{ inputs.package-directory }}
      version: ${{ inputs.version }}
      registry: ${{ inputs.registry }}
      tag: ${{ inputs.tag }}
      node-version: "24"
    secrets:
      npm-token: ${{ secrets._NPM_TOKEN }}
