name: Release dry run

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package location
        required: true
        default: packages/css-color-parser
        type: string
      version-mode:
        description: Release version mode
        required: true
        default: bump
        type: choice
        options:
          - bump
          - package-json
          - exact
      version-bump:
        description: Release bump
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease
      exact-version:
        description: Exact SemVer (used when mode is exact)
        required: false
        default: ""
        type: string

permissions:
  contents: read
  packages: read

jobs:
  release-dry-run:
    uses: moyarich/actions/.github/workflows/reusable_npm-release.yml@c37643656679bec74b2702fc61bf043fe23c0aa7
    with:
      dry-run: true
      package: ${{ inputs.package }}
      version-mode: ${{ inputs.version-mode }}
      version-bump: ${{ inputs.version-bump }}
      exact-version: ${{ inputs.exact-version }}
      publish: false
      node-version: "24"
